spring.application.name=mcpserverstdio
spring.profiles.active=http
server.port=8090


spring.datasource.url=jdbc:postgresql://localhost:5432/mcpserverstdio
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root
#spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update


